### ISSUE TITLE
Signal handled: Terminated when restarting docker

### ISSUE THREAD

**Issue by marcwaz** [docker-library/memcached#26]
My environment is: ubuntu 16.04 + docker 17.06.2-ce
After starting a memchache container and then restarting docker (service docker restart), I noticed that the docker logs command return: 

Signal handled: Terminated.

I suggest also to add close to the end of the Dockerfile, the following command:
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

**Comment by yosifkit** [comment]
I'm not sure I see the correlation between A) `docker logs -f` exiting when the docker itself is restarted and B) "this file needs a `chmod +x`".

A) that is normal since it is the docker daemon process streaming the logs to your terminal
B) the file is already executable in git, so no chown necessary
