### ISSUE TITLE
tell users how to get root

### ISSUE THREAD

**Issue by grosser** [docker-library/memcached#29]
tried to copy-paste some `apt-get install` and it did not work ... and sudo or su also don't work ... so please add some docs on that topic

something like: `This container runs as memcached user by default, to gain root access use "docker run -u root"`

**Comment by yosifkit** [comment]
This is a normal Docker nuance when the image you are using defines `USER` to something other than root and not something specific to the memcached image.  In fact, there are quite a few images that use `USER` to define the running user, rather than something like `gosu` or `su-exec` in an entrypoint script: arangodb, eggdrop, jenkins, nuxeo, plone, sentry. solr, irssi, rocket.chat, and wordpress:cli.
