### ISSUE TITLE
Monitor the service

### ISSUE THREAD

**Issue by Glideh** [docker-library/memcached#33]
I have an application that stores its user sessions in memcached (`1.5.2`).
It is currently complaining about not being able to write (seems to happen randomly)
I'd like to check the queries received by the service.
This does not seem to show anything

    $ docker-compose logs -f memcached

Is there a log somewhere (I don't see any `memcached*` in `/var/log/`) or a verbose mode that we could activate ?
I also tried the `stats` command with telnet but nothing seems to be captured.

**Comment by guillaumeprevost** [comment]
+1

**Comment by tianon** [comment]
(Closing, since this is a general `memcached` configuration question, not an issue with the image. :+1:  
In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).)
